<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Quotation {{ $quotation->quotation_no }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #000;
        }

        .header,
        .footer {
            width: 100%;
            text-align: center;
        }

        .company-info {
            text-align: right;
            font-size: 11px;
        }

        .client-info {
            margin-top: 20px;
        }

        .client-info strong {
            display: inline-block;
            width: 120px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
            font-size: 12px;
        }

        th {
            background-color: #f2f2f2;
        }

        .text-right {
            text-align: right;
        }

        .totals {
            margin-top: 10px;
            width: 50%;
            float: right;
        }

        .totals table {
            border: none;
        }

        .totals td {
            border: none;
            padding: 3px 6px;
        }

        .notes {
            margin-top: 50px;
            font-size: 11px;
        }
    </style>
</head>

<body>

    {{-- Header --}}
    <div class="header">
        <h2>{{ $settings['company_name'] ?? 'Company Name' }}</h2>
        <div class="company-info">
            {{ $settings['company_address'] ?? '' }}<br>
            Phone: {{ $settings['company_phone'] ?? '' }}<br>
            VAT: {{ $settings['company_vat'] ?? '' }}
        </div>
    </div>

    <hr>

    {{-- Quotation Info --}}
    <div>
        <h3>Quotation</h3>
        <strong>No:</strong> {{ $quotation->quotation_no }}<br>
        <strong>Date:</strong> {{ $quotation->quotation_date->format('d M Y') }}<br>
        <strong>Valid Until:</strong> {{ $quotation->valid_until ? $quotation->valid_until->format('d M Y') : '-' }}<br>
        <strong>Prepared By:</strong> {{ $quotation->user->name ?? '-' }}
    </div>

    {{-- Client Info --}}
    <div class="client-info">
        <h4>Client Details</h4>
        <p>
            <strong>Name:</strong> {{ $quotation->client->name ?? '-' }}<br>
            <strong>Email:</strong> {{ $quotation->client->email ?? '-' }}<br>
            <strong>Phone:</strong> {{ $quotation->client->phone ?? '-' }}<br>
            <strong>Address:</strong> {{ $quotation->client->address ?? '-' }}
        </p>
    </div>

    {{-- Items Table --}}
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Product</th>
                <th>Unit Price ({{ $settings['currency_symbol'] ?? 'SAR' }})</th>
                <th>Qty</th>
                <th>Discount ({{ $settings['currency_symbol'] ?? 'SAR' }})</th>
                <th>Total ({{ $settings['currency_symbol'] ?? 'SAR' }})</th>
            </tr>
        </thead>
        <tbody>
            @foreach($quotation->items as $index => $item)
            <tr>
                <td>{{ $index+1 }}</td>
                <td>{{ $item->product_name ?? ($item->product->name ?? '-') }}</td>
                <td class="text-right">{{ number_format($item->unit_price,2) }}</td>
                <td class="text-right">{{ $item->qty }}</td>
                <td class="text-right">{{ number_format($item->discount ?? 0,2) }}</td>
                <td class="text-right">{{ number_format($item->subtotal,2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    {{-- Totals --}}
    <div class="totals">
        <table>
            <tr>
                <td>Subtotal:</td>
                <td class="text-right">{{ number_format($quotation->subtotal,2) }}</td>
            </tr>
            <tr>
                <td>Discount:</td>
                <td class="text-right">{{ number_format($quotation->discount,2) }}</td>
            </tr>
            <tr>
                <td>Tax ({{ $quotation->tax_percent }}%):</td>
                <td class="text-right">{{ number_format($quotation->tax,2) }}</td>
            </tr>
            <tr>
                <td><strong>Total:</strong></td>
                <td class="text-right"><strong>{{ number_format($quotation->total,2) }}</strong></td>
            </tr>
        </table>
    </div>

    {{-- Notes --}}
    @if($quotation->notes)
    <div class="notes">
        <strong>Notes:</strong><br>
        {{ $quotation->notes }}
    </div>
    @endif

    <hr>
    <div class="footer">
        <small>Generated by {{ $settings['company_name'] ?? 'Company Name' }} System</small>
    </div>

</body>

</html>